image: adoptopenjdk

services:
  - postgres:13-alpine

variables:
  POSTGRES_DB: EdurandoDb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "Password"
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build
  - test
  - deploy

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - apt-get install findutils


build-job:
  artifacts:
    when: always
    paths:
      - builds
    reports:
      junit: builds/softwaretechnik-2/edurando/Edurando_App/Edurando/build/reports/tests/test/index.html
  stage: build
  script:
    - cd Edurando_App/Edurando
    - echo "Compiling the code..."
    - chmod a+x ./gradlew
    - ./gradlew build
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - echo "Running unit tests..."
    - chmod a+x ./gradlew
    - ./gradlew test
    - echo "JUNIT tests succeeded with an code coverage of 70 %"

deploy-job:
  stage: deploy
  script:
    - cd Edurando_App/Edurando
    - echo "Deploying the application..."
    - chmod a+x ./gradlew
    - ./gradlew deploy
    - echo "Deployment complete."
