image: gradle:alpine

stages:
  - build
  - test
  - deploy


build-job:
  stage: build
  image: openjdk:17
  script:
    - cd Edurando_App/Edurando
    - chmod a+x ./gradlew
    - ./gradlew build

unit-test-job:
  stage: test
  image: openjdk:17
  script:
    - cd Edurando_App/Edurando
    - chmod a+x ./gradlew
    - ./gradlew test

deploy-job:
  stage: deploy
  image: openjdk:17
  script:
    - cd Edurando_App/Edurando
    - chmod a+x ./gradlew
    - ./gradlew deploy
