stages:
  - build
  - test
  - deploy
image: php:5.6

before_script:
  - apk add findutils

build-job:
  stage: build
  image: openjdk:17
  script:
    - cd Edurando_App/Edurando
    - chmod +x ./gradlew
    - ./gradlew build

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - chmod +x ./gradlew
    - ./gradlew test

deploy-job:
  stage: deploy
  variables:
    JAVA_HOME: "/mnt/c/Program Files/Common Files/Oracle/Java/"
  script:
    - cd Edurando_App/Edurando
    - chmod +x ./gradlew
    - ./gradlew deploy
