stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd Edurando_App/Edurando
    - ./gradlew build

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - ./gradlew test

deploy-job:
  stage: deploy
  script:
    - cd Edurando_App/Edurando
    - ./gradlew deploy
