image: adoptopenjdk


stages:
  - build
  - test
  - deploy

variables:
  DATABASE_HOST: 18b6f1b24061
  DATABASE_PORT: 5432
  DATABASE_NAME: postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: Password

build-job:
  stage: build
  script:
    - cd Edurando_App/Edurando
    - echo "Compiling the code..."
    - chmod a+x ./gradlew
    - ./gradlew build 
    - echo "Compile complete."
   

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - echo "Running unit tests..."
    - ./gradlew test
    - echo "Code coverage is about 70 %"

deploy-job:
  stage: deploy
  script:
    - cd Edurando_App/Edurando
    - echo "Deploying application..."
    - ./gradlew deploy
    - echo "Application successfully deployed."
