stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd Edurando_App/Edurando
    - gradle build --no-daemon

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - gradle test --no-daemon

deploy-job:
  stage: deploy
  script:
    - echo "Deploying to production server"
