image: openjdk:17

stages:
  - build
  - test
  - deploy

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - apt-get install findutils


build-job:
  stage: build
  script:
    - cd Edurando_App/Edurando
    - chmod a+x ./gradlew
    - ./gradlew build

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - chmod a+x ./gradlew
    - ./gradlew test

deploy-job:
  stage: deploy
  script:
    - cd Edurando_App/Edurando
    - chmod a+x ./gradlew
    - ./gradlew deploy
