stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
  script:
    - cd Edurando_App/Edurando
    - chmod +x ./gradlew
    - ./gradlew build

unit-test-job:
  stage: test
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
  script:
    - cd Edurando_App/Edurando
    - chmod +x ./gradlew
    - ./gradlew test

deploy-job:
  stage: deploy
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
  script:
    - cd Edurando_App/Edurando
    - chmod +x ./gradlew
    - ./gradlew deploy
