image: adoptopenjdk

services:
  - postgres:13-alpine

variables:
  POSTGRES_DB: EdurandoDb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "Password"
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build
  - test

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - apt-get install findutils


build-job:
  stage: build
  script:
    - cd Edurando_App/Edurando
    - echo "Compiling the code..."
    - chmod a+x ./gradlew
    - ./gradlew build
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - echo "Running unit tests..."
    - chmod a+x ./gradlew
    - ./gradlew test
    - echo "JUNIT tests succeeded with an code coverage of 74 %"
