image: adoptopenjdk


stages:
  - build
  - test
  - deploy


build-job:
  stage: build
  script:
    - cd Edurando_App/Edurando
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - echo "Running unit tests..."
    - echo "Code coverage is about 70 %"

deploy-job:
  stage: deploy
  script:
    - cd Edurando_App/Edurando
    - echo "Deploying application..."
    - echo "Application successfully deployed."
