stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd Edurando_App/Edurando
    - ./gradlew.bat build

unit-test-job:
  stage: test
  script:
    - cd Edurando_App/Edurando
    - ./gradlew.bat test

deploy-job:
  stage: deploy
  script:
    - cd Edurando_App/Edurando
    - ./gradlew.bat deploy
